num_worktrees = 8

resources = [
    # Don't spin up a billion VMs at once
    { name = "qemu_throttle", count = 8 },
]

[[tests]]
name = "build_min"
cache = "by_tree"
command = """
set -eux
exec 2>&1

make -j tinyconfig
scripts/config -e 64BIT -e -WERROR -e OBJTOOL_WERROR
make -j olddefconfig
CCACHE_SLOPPINESS=time_macros make -sj8 vmlinux CC='ccache gcc' KBUILD_BUILD_TIMESTAMP= 2>&1
"""

[[tests]]
name = "build"
cache = "by_tree"
depends_on = ["build_min"]  # Hack for prioritizing quick feedback
command = """
set -eux
exec 2>&1

# TODO: we can probably use a smaller config
vng --kconfig
scripts/config -e GUP_TEST -e USERFAULTFD
if git grep -q MITIGATION_ADDRESS_SPACE_ISOLATION; then
    scripts/config -d PARAVIRT -e CPU_MITIGATIONS -e MITIGATION_ADDRESS_SPACE_ISOLATION
    make -j olddefconfig
    grep -q MITIGATION_ADDRESS_SPACE_ISOLATION .config
fi
CCACHE_SLOPPINESS=time_macros make -sj100 CC='ccache gcc' KBUILD_BUILD_TIMESTAMP= 2>&1

# We'd like to have the kselftest and kernel builds in separate jobs but it's
# annoying to build modules without a freshly compiled kernel tree.
make -sj100 CC='ccache gcc' -C tools/testing/selftests \
  TARGETS="mm" FORCE_TARGETS=1 EXTRA_CFLAGS=-Werror LDFLAGS=-static \
  install INSTALL_PATH=$LIMMAT_ARTIFACTS/kselftest_install KDIR=$PWD

make kernelrelease > $LIMMAT_ARTIFACTS/kernelrelease.txt
cp arch/x86/boot/bzImage $LIMMAT_ARTIFACTS
cp .config $LIMMAT_ARTIFACTS/config.txt
"""

[[tests]]
name = "kselftests"
cache = "by_tree"
depends_on = ["build"]
resources = ["qemu_throttle"]
requires_worktree = false
error_exit_codes = [123]
command = """
set -eux
exec 2>&1

if ! which -s vng; then
    echo "vng binary not in PATH, see README.md"
    exit 123
fi

rootfs="$(dirname $LIMMAT_CONFIG)/mkosi-rootfs/image/"
if [[ ! -e "$rootfs/usr/bin" ]]; then
    echo "rootfs not set up at $rootfs, see README.md"
    exit 123
fi

kernel="$LIMMAT_ARTIFACTS_build"/bzImage

# Can't mount multiple directories using vng
# https://github.com/arighi/virtme-ng/issues/237
# Workaround by copying everything into a single directory
cp -r "$LIMMAT_ARTIFACTS_build/kselftest_install" "$LIMMAT_ARTIFACTS"

# Embed the runner script here so we get the benefit of local-ci's cache
# invalidation logic
cat <<EOF > "$LIMMAT_ARTIFACTS/run.sh"
set -ex
exec 2>&1

mkdir -p /mnt/kselftest_logs

# We actually want --per-test-log but I wanna be able to test on kernels before that flag existed.
# --summary will try to write to /mnt/kselftest_install which is read-only so that doesn't work either.
# Don't run userfaultfd because I see failures to do hugetlb 1G mmaps in uffd-mp-mremap, even if I
# set --memory 64G. Seems like hugetlb_reserve_pages() is failing but I'm not sure why.
cd /mnt/kselftest_install/mm
for type in mmap gup_test compaction migration page_frag; do
    ./run_vmtests.sh -t \\$type | tee /mnt/kselftest_logs/vmtests_\\$type.log || true
done

# run_kselftest.sh doesn't fail when tests fail. Grep log instead.
if grep "not ok" /mnt/kselftest_logs/*.log; then exit 1; fi
exit 0
EOF

chmod +x "$LIMMAT_ARTIFACTS/run.sh"

unshare -r vng --no-virtme-ng-init --verbose --user root --root "$(dirname $LIMMAT_CONFIG)/mkosi-rootfs/image"  \
    --memory 4G --run "$kernel" --rwdir=/mnt="$LIMMAT_ARTIFACTS" -- "/mnt/run.sh"
"""

[[tests]]
name = "kunit"
cache = "by_tree"
command = """
set -eux
exec 2>&1

git clean -fdx -e .vscode >/dev/null # mrproper isn't always good enough

kunit_run() {
    tools/testing/kunit/kunit.py run --make_options "CC=ccache gcc" "$@"
}

# # Random sample of tests (disabled, too slow)
# kunit_run --kunitconfig ./lib/kunit/.kunitconfig
# kunit_run --kunitconfig ./security/landlock/.kunitconfig
# kunit_run --kunitconfig ./fs/ext4/.kunitconfig

if [ -e mm/.kunitconfig ]; then
    # Run my mm KUnit tests
    # https://lore.kernel.org/linux-mm/20250224-page-alloc-kunit-v1-0-d337bb440889@google.com/
    kunit_run --kunitconfig ./mm/.kunitconfig \
        --arch=x86_64 --kernel_args="movablecore=2G asi=on" \
        --qemu_args="-m 4G" --kunitconfig mm/.kunitconfig

    # Now run them with ASI. Here we're taking advantage of the leftover kunitconfig
    # from the previous step.
    if git grep -q MITIGATION_ADDRESS_SPACE_ISOLATION; then
        scripts/config --file .kunit/.config -e MITIGATION_ADDRESS_SPACE_ISOLATION
        kunit_run --kunitconfig ./mm/.kunitconfig \
            --arch=x86_64 --kernel_args="movablecore=2G" \
            --qemu_args="-m 4G" --kunitconfig mm/.kunitconfig
        # Check ASI was actually enabled
        grep -q MITIGATION_ADDRESS_SPACE_ISOLATION .kunit/.config
    fi
fi
"""

[[tests]]
name = "checkpatch"
# https://lore.kernel.org/all/20250115-checkpatch-ignore-v2-0-8467750bf713@google.com/
# Run the checked out version so we can get my patch from above
requires_worktree = false # Just run whatever version of checkpatch is currently in the main worktree.
# With this checkpatch feature the result depends on more than just the commit hash.
cache = "no_caching"
command = ["python3", "-c", """
import subprocess
import os

LIMMAT_COMMIT=os.getenv("LIMMAT_COMMIT")

def log_n1(format):
    result = subprocess.run(
        ["git", "log", "-n1", "--format=" + format, LIMMAT_COMMIT],
        capture_output=True, text=True, check=True,
    )
    return result.stdout.strip()

# Linus doesn't sign off his release commits lol.
author = log_n1("%an")
if author == "Linus Torvalds":
    print("Ignoring patch from Linus")
    exit(0)

# Don't complain about b4 cover-letter commits.
raw_msg = log_n1("%B")
if "\\n--- b4-submit-tracking ---\\n" in raw_msg:
    print("Ignoring b4-submit-tracking patch")
    exit(0)

print(raw_msg)

ignore = [
    "FILE_PATH_CHANGES",      # Annoying
    "AVOID_BUG",              # yeah yeah yeah
    "VSPRINTF_SPECIFIER_PX",  # Usually I'm doing this deliberately.
    "COMMIT_LOG_LONG_LINE",   # Too noisy
    "MACRO_ARG_UNUSED",       # Bullshit
    "CONFIG_DESCRIPTION",     # Bullshit
    "COMMIT_MESSAGE",         # yeah yeah yeah
    "LOGGING_CONTINUATION",   # yeah yeah yeah
    "COMPLEX_MACRO",          # yeah yeah yeah
    "LONG_LINE",              # yeah yeah yeah
    "EXPORT_SYMBOL",          # noisy
    "EMBEDDED_FUNCTION_NAME"  # noisy
]

# Ignore more stuff on Google prodkernel trees.
if os.path.exists("./gconfigs"):
    ignore += ["GERRIT_CHANGE_ID", "GIT_COMMIT_ID", "MISSING_SIGN_OFF"]

# Get Checkpatch-ignore tag from commit message.
commit_ignore = log_n1("%(trailers:key=Checkpatch-ignore,valueonly)").strip().split()
print(commit_ignore)
ignore += commit_ignore
print(ignore)

cmd = [
    "scripts/checkpatch.pl", "--git", "--show-types",
    f"--ignore={','.join(ignore)}", "--codespell", LIMMAT_COMMIT
]
print(f"Running: {cmd}")

subprocess.run(cmd, check=True)
"""]